version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - NODE_ENV=dev serverless deploy | tee deploy.out