version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY
      - NODE_ENV=dev serverless deploy | tee deploy.out