EventDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: habit_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S

      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
        -
          AttributeName: habit_id
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      TableName: ${self:custom.config.EVENT_TABLE}

  