Resources:
  HabitDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: habit_id
          AttributeType: S
        -
          AttributeName: created_at
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S

      KeySchema:
        -
          AttributeName: habit_id
          KeyType: HASH
        -
          AttributeName: created_at
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
      GlobalSecondaryIndexes:
        -
          IndexName: UserIndex
          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
            -
              AttributeName: created_at
              KeyType: RANGE

          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

      TableName: ${self:custom.config.HABIT_TABLE}