Resources:
  UserDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: item_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
        -
          AttributeName: push_token
          AttributeType: S
        -
          AttributeName: reminder
          AttributeType: S
        -
          AttributeName: streak
          AttributeType: S
        -
          AttributeName: score
          AttributeType: N


      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
        -
          AttributeName: item_id
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
      GlobalSecondaryIndexes:
        -
          IndexName: EmailIndex
          KeySchema:
            -
              AttributeName: email
              KeyType: HASH
            -
              AttributeName: item_id
              KeyType: RANGE

          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

        -
          IndexName: PushNotificationIndex
          KeySchema:
            -
              AttributeName: push_token
              KeyType: HASH
            -
              AttributeName: reminder
              KeyType: RANGE      
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        
        -
          IndexName: StreakIndex
          KeySchema:
            -
              AttributeName: streak
              KeyType: HASH
            -
              AttributeName: score
              KeyType: RANGE      

          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

      TimeToLiveSpecification:
        Enabled: True
        AttributeName: expiration
      
      TableName: ${self:custom.config.USER_TABLE}